[rule]
description = """
Detects when curl or nscurl is executed as an argument of a shell interpreter via a node parent process. This is a
common technique used by malware to download additional payloads and evade traditional defenses.
"""
id = "1ef77794-f718-4bc0-a846-971c45aa00e7"
license = "Elastic License v2"
name = "Curl Execution via Node"
os_list = ["macos"]
reference = ["https://medium.com/@D00MFist/loads-of-fun-e1f0dac3d4f8"]
version = "1.0.7"

query = '''
process where event.type == "start" and process.parent.name : "node" and
 (
  (process.name : ("sh", "bash", "zsh", "tclsh*") and 
    process.args : "-c" and 
    process.args : ("curl*", "nscurl*")) or 
  (process.name : ("curl", "nscurl"))
 ) and
 not process.args :
           ("curl -sfL https://raw.githubusercontent.com/lokalise/*",
            "*http://elastic:changeme@localhost:5601*",
            "Authorization*",
            "*DELETE*",
            "*127.0.0.1*",
            "localhost:*", "curl -s localhost:*") and
 not process.Ext.effective_parent.executable : "/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal" and
 not (process.command_line : "*https://github.com/zeromq/libzmq/archive*" and
      process.Ext.effective_parent.executable : "/Applications/Visual Studio Code.app/Contents/MacOS/Electron")
'''

min_endpoint_version = "8.7.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1105"
name = "Ingress Tool Transfer"
reference = "https://attack.mitre.org/techniques/T1105/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "8.7.0"
