[rule]
description = """
Detects the use of curl to a Google Script endpoint for the purpose of downloading a second stage payload or tool.
Threat actors will utilize an exposed Google Script endpoint to host their payload or tool. Google urls are generally
whitelisted and not seen as suspicious so it's a good way to ensure the download of a payload and via curl which does
not enforce Gatekeeper checks.
"""
id = "c1c58c0a-192c-4360-9264-916725bb1002"
license = "Elastic License v2"
name = "Suspicious Curl to Google App Script Endpoint"
os_list = ["macos"]
reference = ["https://www.google.com/script/start/", "https://attack.mitre.org/techniques/T1105/"]
version = "1.0.16"

query = '''
process where event.type == "start" and process.name : ("curl", "nscurl") and process.args : "https://script.google.com/*"
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1105"
name = "Ingress Tool Transfer"
reference = "https://attack.mitre.org/techniques/T1105/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "7.15.0"
