[rule]
description = """
Identifies DNS queries to common web services by a signed Microsoft binary execution proxy. Adversaries may implement
command and control communications that use common web services in order to hide their activity.
"""
id = "c567240c-445b-4000-9612-b5531e21e050"
license = "Elastic License v2"
name = "Connection to WebService by a Signed Binary Proxy"
os_list = ["windows"]
version = "1.0.47"

query = '''
sequence by process.entity_id with maxspan=5m
  [process where event.action == "start" and user.id : "S-1-5-21-*" and
    (
     process.name : ("wscript.exe", "cscript.exe", "regsvr32.exe", "mshta.exe", "rundll32.exe", "vbc.exe",
                     "msbuild.exe", "wmic.exe", "cmstp.exe", "RegAsm.exe", "installutil.exe","RegSvcs.exe",
                     "msxsl.exe", "xwizard.exe", "csc.exe", "curl.exe", "net.exe", "certutil.exe", "wmic.exe",
                     "ssh.exe", "scp.exe") or
     process.pe.original_file_name : ("wscript.exe", "cscript.exe", "regsvr32.exe", "mshta.exe", "rundll32.exe", 
                                      "vbc.exe", "msbuild.exe", "wmic.exe", "cmstp.exe", "RegAsm.exe", "installutil.exe", 
                                      "RegSvcs.exe", "msxsl.exe", "xwizard.exe", "csc.exe", "curl.exe", "net.exe",
                                      "certutil.exe", "wmic.exe") or
     process.executable : ("?:\\Program Files\\Java\\jre*\\bin\\javaw.exe",
                           "?:\\Program Files (x86)\\Java\\jre*\\bin\\javaw.exe",
                           "?:\\Windows\\Microsoft.NET\\*.exe") or
     ((process.name : "powershell.exe" or process.pe.original_file_name == "PowerShell.EXE") and process.args_count >= 2)
     ) and
     not (process.name : "rundll32.exe" and process.command_line : "*davclnt.dll,DavSetCookie*") and
     not (process.parent.executable : ("?:\\Program Files\\Microsoft SQL Server\\MSSQL*.EXE", "?:\\Program Files\\WindowsApps\\Microsoft.*.exe") and
          process.name : ("powershell.exe", "pwsh.exe")) and
     not (process.name : "java.exe" and process.parent.executable : "?:\\Program Files\\OWASP\\Zed Attack Proxy\\ZAP.exe") and
     not (process.name : "java.exe" and process.args_count >= 5) and
     not process.executable : ("?:\\Program Files\\Microsoft Visual Studio\\*\\MSBuild.exe", "?:\\Program Files (x86)\\Microsoft Visual Studio\\*\\MSBuild.exe") and
     not (process.name : "javaw.exe" and
          process.parent.executable : ("?:\\Program Files\\QZ Tray\\qz-tray.exe", "?:\\Program Files (x86)\\PGP Tool\\pgptool.exe", "?:\\Program Files\\OWASP\\Zed Attack Proxy\\ZAP.exe")) and
     not (process.name : "rundll32.exe" and process.args : "?:\\WINDOWS\\Installer\\MSI*.tmp,zzzzInvokeManagedCustomActionOutOfProc") and
     /* BlueIris - Camera IOT monitoring sw using telegram to upload pictures */
     not (process.name : "curl.exe" and process.parent.name : "cmd.exe" and process.parent.args : "C:\\BlueIris\\Telegram-Upload\\upload.cmd ") and
     not (process.name : "curl.exe" and process.parent.executable : "?:\\Program Files\\Neovim\\bin\\nvim.exe") and
     not (process.name : "rundll32.exe" and
          process.args : ("?:\\Program Files\\Microsoft Office\\root\\*",
                          "?:\\PROGRA~2\\MICROS~1\\Office*.CPL*",
                          "?:\\Program Files (x86)\\F5 VPN\\*",
                          "?:\\Program Files\\F5 VPN\\*",
                          "?:\\Program Files (x86)\\Microsoft Office\\root\\*",
                          "?:\\Windows\\system32\\shell32.dll,Control_RunDLL",
                          "?:\\WINDOWS\\SYSTEM32\\EDGEHTML.dll,#141",
                          "?:\\WINDOWS\\System32\\shell32.dll,SHCreateLocalServerRunDll",
                          "?:\\PROGRA~2\\MICROS~2\\Office*\\*.CPL*",
                          "?:\\Windows\\System32\\mshtml.dll,PrintHTML", 
                          "?:\\PROGRA~?\\MICROS~?\\Office??\\MLCFG32.CPL,@0", 
                          "AppXDeploymentExtensions.OneCore.dll,ShellRefresh")) and 
      not process.parent.executable : ("C:\\Program Files\\Logi\\LogiBolt\\LogiBolt.exe", "C:\\Program Files (x86)\\Avaya\\Avaya one-X Agent\\OneXAgentUI.exe")
  ]
  [dns where
    dns.question.name :
    (
        "raw.githubusercontent.*",
        "pastebin.*",
        "paste.ee",
        "ghostbin.com",
        "drive.google.com",
        "?.docs.live.net",
        "api.dropboxapi.*",
        "content.dropboxapi.*",
        "dl.dropboxusercontent.*",
        "api.onedrive.com",
        "*.onedrive.org",
        "onedrive.live.com",
        "storage.googleapis.com",
        "filebin.net",
        "*.ngrok.io",
        "ngrok.com",
        "*.portmap.*",
        "*serveo.net",
        "*localtunnel.me",
        "*pagekite.me",
        "*localxpose.io",
        "*notabug.org",
        "rawcdn.githack.*",
        "paste.nrecom.net",
        "zerobin.net",
        "controlc.com",
        "requestbin.net",
        "slack.com",
        "api.slack.com",
        "slack-redir.net",
        "slack-files.com",
        "cdn.discordapp.com",
        "discordapp.com",
        "discord.com",
        "apis.azureedge.net",
        "cdn.sql.gg",
        "?.top4top.io",
        "top4top.io",
        "www.uplooder.net",
        "*.cdnmegafiles.com",
        "transfer.sh",
        "updates.peer2profit.com",
        "api.telegram.org",
        "t.me",
        "meacz.gq",
        "rwrd.org",
        "*.publicvm.com",
        "*.blogspot.com",
        "api.mylnikov.org",
        "script.google.com",
        "script.googleusercontent.com",
        "paste4btc.com",
        "workupload.com",
        "temp.sh",
        "filetransfer.io",
        "gofile.io",
        "store?.gofile.io",
        "tiny.one",
        "api.notion.com",
        "graph.microsoft.com",
        "*.sharepoint.com",
        "*upload.ee",
        "bit.ly",
        "t.ly",
        "cutt.ly",
        "mbasic.facebook.com",
        "login.live.com",
        "login.microsoftonline.com",
        "api.gofile.io",
        "file.io",
        "api.anonfiles.com",
        "api.trello.com",
        "api.notion.com",
        "gist.githubusercontent.com",
        "dpaste.com",
        "*azurewebsites.net",
        "*.zulipchat.com",
        "*.4shared.com",
        "filecloud.me",
        "i.ibb.co",
        "files.catbox.moe",
        "*.getmyip.com",
        "files.pythonhosted.org",
        "mockbin.org",
        "webhook.site",
        "run.mocky.io",
        "*infinityfreeapp.com",
        "free.keep.sh",
        "tinyurl.com",
        "ftpupload.net",
        "lobfile.com",
        "*.ngrok-free.app",
        "www.myexternalip.com",
        "yandex.ru",
        "*.yandex.ru",
        "*.aternos.me",
        "cdn??.space",
        "*.pcloud.com",
        "mediafire.zip",
        "urlz.fr",
        "api.github.com",
        "rentry.co"
    ) and
    /* common to use powershell script by Microsoft Cloud sysadmins */
    not (process.name : ("powershell.exe", "pwsh.exe", "javaw.exe") and
         dns.question.name : ("graph.microsoft.com", "*.sharepoint.com", "login.microsoftonline.com", "login.live.com", "raw.githubusercontent.com", "api.github.com")) and
    not (dns.question.name : "rev-resolve.azurewebsites.net" and process.name : "wscript.exe")
  ]
'''

min_endpoint_version = "7.15.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 1

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 1

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1218"
name = "System Binary Proxy Execution"
reference = "https://attack.mitre.org/techniques/T1218/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1071"
name = "Application Layer Protocol"
reference = "https://attack.mitre.org/techniques/T1071/"
[[threat.technique.subtechnique]]
id = "T1071.004"
name = "DNS"
reference = "https://attack.mitre.org/techniques/T1071/004/"


[[threat.technique]]
id = "T1102"
name = "Web Service"
reference = "https://attack.mitre.org/techniques/T1102/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "7.15.0"
