[rule]
description = """
Detects the unusual use of curl to download an archived file in order to deliver additional tooling or payload stages.
Many threat actors have been seen utilizing curl to download this archive file. Use of curl in this way while not
inherently malicious should be considered highly abnormal and suspicious activity.
"""
id = "5c5bcd83-1734-4d5e-a027-09aaf485b837"
license = "Elastic License v2"
name = "MacOS Suspicious Archive File Download via Curl"
os_list = ["macos"]
version = "1.0.8"

query = '''
process where event.type == "start" and event.action == "exec" and process.name : "curl" and
process.args : ("-L", "--location") and
process.args : ("-k",  "--insecure") and
process.args : ("-o", "--output") and 
process.args : ("/*.zip", "/*.gz", "/*.tgz") and 
process.args : "http*" and 
not process.args : ("http*://localhost*", 
                    "https://*.newrelic.com*",
                    "x-app-license-key*",
                    "--user-agent",
                    "*github.com/elastic/*",
                    "http*://127.0.0.1*", 
                    "http*://0.0.0.0*") and 
not process.parent.executable : "/Library/Developer/*" and
not process.Ext.effective_parent.executable : "/Library/Application Support/Mosyle/MosyleMDM.app/Contents/MacOS/MosyleMDM"
'''

min_endpoint_version = "8.5.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1105"
name = "Ingress Tool Transfer"
reference = "https://attack.mitre.org/techniques/T1105/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "8.5.0"
