[rule]
description = """
Identifies the execution of a low reputation file spawned by the ScreenConnect client processes. This activity may
indicate execution abusing unauthorized access to the ScreenConnect remote access software.
"""
id = "b9972afd-5195-4ed3-94ba-3785a9e87a38"
license = "Elastic License v2"
name = "Execution of a Low Reputation File via ScreenConnect"
os_list = ["windows"]
reference = [
    "https://www.huntress.com/blog/slashandgrab-screen-connect-post-exploitation-in-the-wild-cve-2024-1709-cve-2024-1708",
]
version = "1.0.2"

query = '''
process where host.os.type == "windows" and event.type == "start" and
 (process.Ext.relative_file_creation_time <= 500 or process.Ext.relative_file_name_modify_time <= 500) and
 (process.code_signature.trusted == false or process.code_signature.exists == false) and
  (
   process.parent.name : ("ScreenConnect.ClientService.exe", "ScreenConnect.WindowsClient.exe",
                          "ScreenConnect.WindowsBackstageShell.exe", "ScreenConnect.WindowsFileManager.exe",
                          "ScreenConnect.Service.exe") or
   descendant of [process where event.action == "start" and
                  process.name : ("ScreenConnect.ClientService.exe", "ScreenConnect.WindowsClient.exe",
                                  "ScreenConnect.WindowsBackstageShell.exe", "ScreenConnect.WindowsFileManager.exe",
                                  "ScreenConnect.Service.exe")]
  )
'''

min_endpoint_version = "8.10.0"
reputation = true
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1219"
name = "Remote Access Software"
reference = "https://attack.mitre.org/techniques/T1219/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "8.10.0"
