[rule]
description = """
Identifies unusual processes connecting to domains using known free SSL certificates. Adversaries may employ free HTTP
SSL certificates to conceal command and control traffic.
"""
id = "88f6c3d4-112e-4fad-b3ef-33095c954b63"
license = "Elastic License v2"
name = "Suspicious DNS Query to Free SSL Certificate Domains"
os_list = ["windows"]
version = "1.0.24"

query = '''
sequence by process.entity_id with maxspan=5m
 [process where event.action == "start" and
  (
   (process.Ext.device.product_id : ("Virtual DVD-ROM", "Virtual Disk", "USB *") and not process.executable : "C:\\*") or
   process.executable :
         ("?:\\Windows\\system32\\*",
		  "?:\\Windows\\SysWOW64\\*",
		  "?:\\Windows\\Microsoft.NET\\Framework*.exe",
		  "?:\\Windows\\explorer.exe",
		  "?:\\Windows\\notepad.exe",
		  "?:\\Windows\\Tasks\\*",
		  "?:\\Windows\\Temp\\*", 
		  "?:\\Users\\*\\AppData\\Local\\Temp\\Temp?_*", 
		  "?:\\Users\\*\\AppData\\Local\\Temp\\7z*", 
		  "?:\\Users\\*\\AppData\\Local\\Temp\\Rar*", 
		  "?:\\Users\\*\\AppData\\Local\\Temp\\BNZ.*") or 
   (process.executable : ("?:\\Users\\*", "?:\\ProgramData\\*") and process.Ext.relative_file_creation_time <= 500)
   ) and
   not process.executable :
         ("?:\\Windows\\System32\\drivers\\RivetNetworks\\Killer\\KillerNetworkService.exe",
		  "?:\\Windows\\System32\\lsass.exe",
		  "?:\\Windows\\System32\\svchost.exe",
		  "?:\\Windows\\System32\\backgroundTaskHost.exe",
		  "?:\\Windows\\SystemApps\\*.exe",
		  "?:\\Windows\\explorer.exe", 
		  "?:\\Windows\\System32\\svchost.exe", 
		  "?:\\Windows\\System32\\AppHostRegistrationVerifier.exe", 
		  "?:\\Windows\\System32\\MicrosoftEdgeCP.exe", 
		  "?:\\Windows\\System32\\inetsrv\\InetMgr.exe", 
		  "?:\\Windows\\System32\\wbem\\WmiPrvSE.exe", 
		  "?:\\Windows\\SysWOW64\\wbem\\WmiPrvSE.exe",
		  "?:\\Windows\\System32\\taskhostw.exe", 
		  "?:\\Windows\\System32\\WWAHost.exe",
		  "?:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\*\\MsMpEng.exe", 
		  "?:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\*\\NisSrv.exe", 
		  "?:\\Windows\\System32\\WindowsPowerShell\\v*\\powershell.exe", 
		  "?:\\Windows\\System32\\inetsrv\\w3wp.exe", 
		  "?:\\Windows\\SysWOW64\\inetsrv\\w3wp.exe",
		  "?:\\Windows\\System32\\AuthHost.exe", 
		  "?:\\Windows\\SysWOW64\\WuWUI.exe", 
		  "?:\\Windows\\System32\\msfeedssync.exe",
		  "?:\\Windows\\System32\\omadmclient.exe",
		  "?:\\Windows\\System32\\DeviceCensus.exe",
		  "?:\\Windows\\System32\\smartscreen.exe",
		  "?:\\Windows\\System32\\ipconfig.exe",
		  "?:\\Windows\\SysWOW64\\ipconfig.exe",
		  "?:\\Windows\\System32\\SIHClient.exe",
		  "?:\\Windows\\System32\\WinBioPlugIns\\FaceFodUninstaller.exe",
		  "?:\\Windows\\system32\\WerFault.exe",
		  "?:\\Windows\\system32\\schtasks.exe",
		  "?:\\Windows\\System32\\Speech_OneCore\\Common\\SpeechRuntime.exe",
		  "?:\\Windows\\System32\\BackgroundTransferHost.exe",
		  "?:\\Windows\\System32\\mousocoreworker.exe",
		  "?:\\WINDOWS\\system32\\compattelrunner.exe") and
   not (process.executable :
              ("?:\\Windows\\Sys*\\ping.exe",
               "?:\\Windows\\system32\\nslookup.exe") and process.args_count >= 2) and
   not (process.name : "rundll32.exe" and
         process.args :
                    ("?:\\windows\\system32\\davclnt.dll,DavSetCookie",
	                 "?:\\Windows\\SysWOW64\\davclnt.dll,DavSetCookie",
	                 "cryptext.dll,CryptExtOpenCER",
	                 "cryptext.dll,CryptExtAddCER",
	                 "?:\\Windows\\system32\\cryptext.dll,CryptExt*",
	                 "?:\\Windows\\System32\\LogiLDA.dll,LogiFetch")) and
   not (process.executable : ("?:\\Users\\*", "?:\\ProgramData\\*") and process.code_signature.trusted == true) and 
   not (process.pe.original_file_name : "NetworkOnboardingClient.dll" and process.code_signature.trusted == true) and 
   not process.hash.sha256 : 
               ("edd0a64dc65087ffe453ca94b267169b39458a983b29ac31320fcaa983d0f97e",
                "316fbec9eca41deef9a63837dfaf4de4369ca507c5b2143cd3a805cb238e5057",
                "b653d77479b36e9d804a5e8ca78adbbfe9ce0b82fd8e45512cf7f3ad175b945c",
                "f28aad782bc6f10f3e27a5c07b7a3d3cc3b3ec3805eaaaf4db5f311882caa91f",
                "96bd6636458bd2c3f020c7cb922058579a2fc8014f587c4617531ddcbc55475a",
                "748d48d246526e2a79edcde87255ffa5387e3bcc94f6ca5e59589e07e683cd80",
                "1c0a4d603fb16b53d733663bde0ebd1e9a593d4c55015301f06e8a01261c1d0d",
                "0a76f94c40fe2f576448432bb65fdd23e2aefbfc2f58478c1d7bb525ff285cd1",
                "0a76f94c40fe2f576448432bb65fdd23e2aefbfc2f58478c1d7bb525ff285cd1",
                "3d9e0143268f52aecaff76f81553c880ec9a353eb5a6e22bd6d34bad8251710c",
                "cc08b9ba4eefdac9d120a69d2a4541908c2ba6d68387589e9e93dddd65a26606", 
		"002a87f6a35a0aa2eca3c89b45b41b922e1aa4c0536a08a8f7f306421f828272", 
                "37d66cf4990eabe4cfa65e4f73d673a03cbce33d1bdf7b64f0b661f4a0872b9a") and
   not (process.name : "rundll32.exe" and process.command_line : "*PcaSvc.dll,PcaPatchSdbTask*" and
        process.parent.executable : "?:\\Windows\\System32\\svchost.exe") and
   not (process.executable : "?:\\WINDOWS\\system32\\wermgr.exe" and
        process.args : "-upload" and process.parent.executable : "?:\\Windows\\System32\\svchost.exe") and
   not (process.code_signature.subject_name : ("Mozilla Corporation", "Google LLC", "Secure By Design Inc.", "Intel(R) pGFX *", 
                                               "Specops Software Inc.", "Flexera Software LLC", "N-ABLE TECHNOLOGIES LTD", "N-ABLE TECHNOLOGIES LTD") and
        process.code_signature.trusted == true) and
   not (process.name : "powershell.exe" and user.id == "S-1-5-18") and
   not (process.executable : "?:\\Windows\\System32\\mstsc.exe" and
        process.parent.executable : "?:\\Windows\\explorer.exe" and
        not process.args :
                   ("?:\\Users\\*\\Downloads\\*",
                    "?:\\Users\\*\\AppData\\Local\\Temp\\Temp?_*",
                    "?:\\Users\\*\\AppData\\Local\\Temp\\7z*",
                     "?:\\Users\\*\\Content.Outlook\\*"))
 ]
 [dns where 
  dns.question.name : ("*letsencrypt.org", "*.sslforfree.com", "*.zerossl.com", "*.freessl.org", "*.lencr.*")]
'''

min_endpoint_version = "8.4.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1204"
name = "User Execution"
reference = "https://attack.mitre.org/techniques/T1204/"
[[threat.technique.subtechnique]]
id = "T1204.002"
name = "Malicious File"
reference = "https://attack.mitre.org/techniques/T1204/002/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1071"
name = "Application Layer Protocol"
reference = "https://attack.mitre.org/techniques/T1071/"

[[threat.technique]]
id = "T1573"
name = "Encrypted Channel"
reference = "https://attack.mitre.org/techniques/T1573/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "8.4.0"
