[rule]
description = """
Identifies when a process running in a suspicious directory, such as the temp directory attempts to download a second
stage payload. This behavior is consistent with malware families such as Bundlore.
"""
id = "04d124d4-2be7-405e-b830-9494f927a51e"
license = "Elastic License v2"
name = "Payload Downloaded by Process Running in Suspicious Directory"
os_list = ["macos"]
reference = ["https://attack.mitre.org/software/S0482/", "https://objective-see.com/blog/blog_0x69.html"]
version = "1.0.33"

query = '''
sequence by process.entity_id with maxspan=30s
  [process where event.action == "exec" and 
   process.name : ("curl", "nscurl") and process.args : "http*://*/*" and 
    descendant of [
      process where event.action : "exec" and
        process.executable : (
          "/tmp/*",
          "/Users/*/Library/Preferences/*",
          "/Users/*/Library/Services/*",
          "/var/tmp/*",
          "/var/folders/*",
          "/var/lib/*",
          "/Users/Shared/*",
          "/Library/Graphics/*",
          "/Library/Containers/*", 
          "/Users/*/Library/Containers/*", 
          "/var/root/*", 
          "/Library/WebServer/*", 
          "/Library/Fonts/*") 
  ] and not 
  process.args : ("https://omahaproxy.appspot.com/history", 
                  "https://console.jumpcloud.com/api/systems/*", 
                  "/usr/local/Homebrew/*",
                  "/opt/jc//jumpcloud-agent.pkg",
                  "Homebrew/*",
                  "*/opt/homebrew/*",
                  "http*://*.jamfcloud.com/*",
                  "http*elastic.co*",
                  "http*localhost*",
                  "http*127.0.0.1*",
                  "http*0.0.0.0*",
                  "*jumpcloud.osquery_manager*",
                  "https://zoom.us/client/*") and 
  not process.parent.executable : ("/usr/local/munki/*",
                                   "/System/*",
                                   "/opt/homebrew/*",
                                   "/Library/Management/*")   
  ]
  [network where event.action == "connection_attempted" and process.name == "curl"]
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1105"
name = "Ingress Tool Transfer"
reference = "https://attack.mitre.org/techniques/T1105/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "7.15.0"
