[rule]
description = """
Detects when a new OsaScript download cradle is spawned as a backgrounded process to launch a new callback. The Apfell
agent payload utilizes this method in order to spawn additional payload callbacks.
"""
id = "c8e816ab-360f-4608-aebf-a056437c7df0"
license = "Elastic License v2"
name = "OsaScript Download Cradle Spawned"
os_list = ["macos"]
reference = [
    "https://github.com/MythicAgents/apfell/blob/master/documentation-payload/apfell/commands/spawn_download_cradle.md",
    "https://github.com/MythicAgents/apfell/",
]
version = "1.0.6"

query = '''
sequence by process.parent.entity_id with maxspan=1m
[process where event.type == "start" and event.action == "fork" and 
 process.name == "osascript" and process.args == "-l" and process.args : "JavaScript"]
[network where event.type == "start" and process.name == "osascript"]
'''

min_endpoint_version = "8.6.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1008"
name = "Fallback Channels"
reference = "https://attack.mitre.org/techniques/T1008/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "8.6.0"
