[rule]
description = """
Detects the use of the Cat binary to access the contents of sensitive Crypto Wallet files. The AMOS malware along with
other stealers have been observed using this technique in order to collect sensitive file data and stage it for
exfiltration.
"""
id = "259d683b-8551-41ce-b101-d0897e530a36"
license = "Elastic License v2"
name = "Crypto Wallet File Access via CommandLine"
os_list = ["macos"]
version = "1.0.1"

query = '''
process where event.type == "start" and event.action == "exec" and process.name : "cat" and 
 process.args : ("/Users/*/.electrum/wallets/*", 
                 "/Users/*/Library/Application_Support/Google/Chrome/Default/Extensions/hnfanknocfeofbddgcijnmhnfnkdnaad/*",
                 "/Users/*/Library/Application Support/Google/Chrome/Default/Extensions/egjidgbpglichdcondbcbdnbeeppgdph/*",
                 "/Users/*/Library/Application Support/Exodus/exodus.wallet", 
                 "/Users/*/Library/Application Support/Coinomi/wallets/*",
                 "/Users/*/Library/Application Support/atomic/Local Storage/leveldb/*",
                 "/Users/*/Library/Application Support/Google/Chrome/Default/Extensions/nkbihfbeogaeaoehlefnkodbefgpgknn/*",
                 "/Users/*/Library/Application Support/Google/Chrome/Default/Extensions/fhilaheimglignddkjgofkcbgekhenbh/*",
                 "/Users/*/Library/Application Support/Google/Chrome/Default/Extensions/odbfpeeihdkbihmopkbjmoonfanlbfcl/*",
                 "/Users/*/Library/Application Support/BraveSoftware/Brave-Browser/BraveWallet/*",
                 "/Users/*/Library/Application Support/BraveSoftware/Brave-Browser/Default/BraveWallet/Brave Wallet Storage/*",
                 "/Users/*/Library/Application Support/Firefox/Profiles/*/extensions/webextension@metamask.io.xpi",
                 "/Users/*/Library/Application Support/Microsoft Edge/Edge Wallet/*",
                 "/Users/*/Library/Application Support/Microsoft Edge/Default/Extensions/ejbalbakoplchlghecdalmeeeajnimhm/*") and
  not process.Ext.effective_parent.executable : "/Library/NessusAgent/run/sbin/nessus-service"
'''

min_endpoint_version = "8.11.1"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1552"
name = "Unsecured Credentials"
reference = "https://attack.mitre.org/techniques/T1552/"
[[threat.technique.subtechnique]]
id = "T1552.001"
name = "Credentials In Files"
reference = "https://attack.mitre.org/techniques/T1552/001/"



[threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

[internal]
min_endpoint_version = "8.11.1"
