[rule]
description = """
Detects when a suspicious process attempts to access a crypto wallet sensitive file. This is an alpha version of this
rule and meant to be used to assess and test.
"""
id = "a3050eae-c8ae-434d-aeff-97112eddcb48"
license = "Elastic License v2"
name = "Crypto Wallet File Access by Unsigned or Untrusted Binary"
os_list = ["macos"]
version = "1.0.9"

query = '''
file where event.action == "open" and 
 file.path : ("/Users/*/.electrum/wallets/*", 
              "/Users/*/Library/Application_Support/Google/Chrome/Default/Extensions/hnfanknocfeofbddgcijnmhnfnkdnaad/*",
              "/Users/*/Library/Application Support/Google/Chrome/Default/Extensions/egjidgbpglichdcondbcbdnbeeppgdph/*",
              "/Users/*/Library/Application Support/Exodus/exodus.wallet", 
              "/Users/*/Library/Application Support/Coinomi/wallets/*",
              "/Users/*/Library/Application Support/atomic/Local Storage/leveldb/*",
              "/Users/*/Library/Application Support/Google/Chrome/Default/Extensions/nkbihfbeogaeaoehlefnkodbefgpgknn/*",
              "/Users/*/Library/Application Support/Google/Chrome/Default/Extensions/fhilaheimglignddkjgofkcbgekhenbh/*",
              "/Users/*/Library/Application Support/Google/Chrome/Default/Extensions/odbfpeeihdkbihmopkbjmoonfanlbfcl/*",
              "/Users/*/Library/Application Support/BraveSoftware/Brave-Browser/BraveWallet/*",
              "/Users/*/Library/Application Support/BraveSoftware/Brave-Browser/Default/BraveWallet/Brave Wallet Storage/*",
              "/Users/*/Library/Application Support/Firefox/Profiles/*/extensions/webextension@metamask.io.xpi",
              "/Users/*/Library/Application Support/Microsoft Edge/Edge Wallet/*",
              "/Users/*/Library/Application Support/Microsoft Edge/Default/Extensions/ejbalbakoplchlghecdalmeeeajnimhm/*") and
  process.executable != null and
  (process.code_signature.trusted == false or process.code_signature.exists == false)
'''

min_endpoint_version = "8.11.1"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1552"
name = "Unsecured Credentials"
reference = "https://attack.mitre.org/techniques/T1552/"
[[threat.technique.subtechnique]]
id = "T1552.001"
name = "Credentials In Files"
reference = "https://attack.mitre.org/techniques/T1552/001/"



[threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

[internal]
min_endpoint_version = "8.11.1"
