[rule]
description = """
Identifies attempts to hook certain memory section mapping related APIs with suspicious properties. This may indicate an
attempt to evade defense leveraging API hooking.
"""
id = "63f3d1c5-7e19-48db-965d-cc2a52e96650"
license = "Elastic License v2"
name = "Suspicious Windows NT API Hooking"
os_list = ["windows"]
version = "1.0.2"

query = '''
api where process.Ext.api.name : "WriteProcessMemory" and process.Ext.api.behaviors : "hook_api" and
 process.Ext.api.summary : "* Self,*" and
 process.Ext.api.summary : ("*ntdll.dll!ZwCreateSection*", "*ntdll.dll!NtCreateSection*", "*ntdll.dll!ZwOpenSection*",
                            "*ntdll.dll!NtOpenSection*", "*ntdll.dll!ZwClose*", "*ntdll.dll!NtClose*", "*ntdll.dll!ZwMapViewOfSection*",
                            "*ntdll.dll!NtMapViewOfSection*", "*ntdll.dll!ZwUnmapViewOfSection*", "*ntdll.dll!NtUnmapViewOfSection*") and
 process.Ext.api.parameters.size == 21  and
 not process.Ext.api.behaviors : ("cross_process", "parent_child") and
 not process.thread.Ext.call_stack_final_user_module.name : "Kernel" and
 not (process.code_signature.status : "trusted" and startswith~(process.thread.Ext.call_stack_final_user_module.name, process.name)) and
 not process.thread.Ext.call_stack_final_user_module.path :
                              ("?:\\Program Files\\*.dll",
                               "?:\\Program Files (x86)\\*.dll",
                               "\\Program Files\\*.dll",
                               "\\Program Files (x86)\\*.dll",
                               "?:\\windows\\system32\\hmpalert.dll",
                               "?:\\windows\\syswow64\\hmpalert.dll",
                               "?:\\windows\\system32\\*\\tmmon*.dll*",
                               "?:\\Windows\\SysWOW64\\esensordbi.dll*",
                               "?:\\Windows\\System32\\esensordbi.dll*",
                               "?:\\Windows\\System32\\umppc*.dll*",
                               "?:\\Windows\\FireEye\\AppMonitorDll*.dll*",
                               "?:\\Windows\\apppatch\\AppPatch*\\exploitblocker.dll*")
'''

min_endpoint_version = "8.10.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
