[rule]
description = """
Identifies attempt to create a heap memory allocation with executable code permission (HEAP_CREATE_ENABLE_EXECUTE
option). This may indicate an attempt to prepare for shellcode injection evading security monitoring for suspicious
VirtualAlloc API calls.
"""
id = "4d21b212-1046-41fc-98f1-b4c175594fb2"
license = "Elastic License v2"
name = "Suspicious Executable Heap Allocation"
os_list = ["windows"]
reference = ["https://learn.microsoft.com/en-us/windows/win32/api/heapapi/nf-heapapi-heapcreate"]
version = "1.0.17"

query = '''
sequence by process.entity_id with maxspan=3m
 [process where event.action == "start" and 
  (
  ((process.Ext.relative_file_creation_time <= 500 or process.Ext.relative_file_name_modify_time <= 500) and
   (process.code_signature.trusted == false or process.code_signature.exists == false)) or 
   process.name : ("rundll32.exe", "regsvr32.exe")
   ) and 
   not process.executable :
             ("?:\\Program Files (x86)\\*.exe",
              "?:\\Program Files\\*.exe",
              "?:\\Windows\\System32\\DriverStore\\FileRepository\\*",
              "E:\\*PortableCase\\Dependencies\\Sandbox\\stubcache\\CefSharp.BrowserSubprocess.exe",
              "C:\\Steam\\steamapps\\common\\Farlight 84\\WindowsClient\\Solarland\\Binaries\\Win64\\SolarlandClient-Win64-Shipping.exe", 
              "?:\\Windows\\System32\\DriverStore\\FileRepository\\icst_service.inf_amd64_*\\intel_cst_helper_service.exe", 
              "?:\\Windows\\Lenovo\\ImController\\Service\\Lenovo.Modern.ImController.exe") and 
 not process.parent.executable : "?:\\Program Files (x86)\\AlwaysUp\\AlwaysUpService.exe"             
 ]
[api where process.Ext.api.name :"VirtualAlloc" and
  process.Ext.api.parameters.protection : "*X*" and process.executable != null and
  _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info: ("*HeapCreate*", "*RtlCreateHeap*", "*RtlProtectHeap*")) and
  process.thread.Ext.call_stack_summary : "?*" and process.thread.Ext.call_stack_final_user_module.path != null and 
  stringcontains~(process.executable, process.thread.Ext.call_stack_final_user_module.path) and 
  not process.thread.Ext.call_stack_summary : 
          ("*|clr.dll|*", "*mscorwks.dll*", "*mscoreei.dll*", "*mscoree.dll|ntdll.dll*", "*coreclr.dll*", 
           "ntdll.dll|hmpalert.dll|ntdll.dll|kernelbase.dll|*", "ntdll.dll|tmmon64.dll|Unknown", 
           "*ntdll.dll|kernelbase.dll|gtsvm.dll", "*ntdll.dll|kernelbase.dll|wd???vm.dll*", 
           "ntdll.dll|tmmon64.dll|Unknown", "ntdll.dll|hmpalert.dll|ntdll.dll|*", "ntdll.dll|kernelbase.dll|d3dcompiler_??.dll|*", 
           "ntdll.dll|kernelbase.dll|microsoft.csharp.ni.dll|*")]
'''

min_endpoint_version = "8.10.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
