[rule]
description = """
Identifies attempt to perform code injection from an unsigned executable abusing Windows Thread Pools structures for
remote code execution.
"""
id = "01985387-cc86-4366-b237-09c529998c0f"
license = "Elastic License v2"
name = "Potential Injection via Windows Thread Pools"
os_list = ["windows"]
reference = ["https://github.com/SafeBreach-Labs/PoolParty/tree/main"]
version = "1.0.4"

query = '''
sequence by process.entity_id
[library where
  (dll.code_signature.trusted == false or dll.code_signature.exists == false) and
  (dll.Ext.relative_file_creation_time <= 3600 or dll.Ext.relative_file_name_modify_time <= 3600)] as event0
[api where
  process.Ext.api.behaviors : "cross-process" and 
  process.thread.Ext.call_stack_final_user_module.name != null and 
  stringcontains~(process.thread.Ext.call_stack_final_user_module.path, event0.dll.path) and 
  (
   (process.Ext.api.name : "WriteProcessMemory" and process.Ext.api.summary : "*Data*" and 
    (process.Ext.api.parameters.size == 72 or process.Ext.api.parameters.size == 296 or process.Ext.api.parameters.size == 288 or process.Ext.api.parameters.size == 240) and 
	 not (process.Ext.api.behaviors : "parent-child" and stringcontains~(process.Ext.api.summary, process.name))) or
	 
   (process.Ext.api.name : "VirtualProtectEx" and process.Ext.api.summary : "*ntdll.dll*R?X|0x20000000*" and 
    _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info: "*TlsGetValue*") and 
	_arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info: ("*ZwProtectVirtualMemory*", "*NtProtectVirtualMemory*")))
   )]
 until [process where event.action:"end"]
'''

min_endpoint_version = "8.10.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 1

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"

[[threat.technique]]
id = "T1574"
name = "Hijack Execution Flow"
reference = "https://attack.mitre.org/techniques/T1574/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
