[rule]
description = """
Detects the potential loading of a dylib from memory by looking for dylib load events without a dll.path present
indicating the dylib was not loaded from disk. Loading a dylib directly into memory is a technique often used by
attackers to evade detection. This is because loading a dylib directly into memory leaves no traces on the disk, making
it harder for security tools or analysts to detect the malicious dylib.
"""
id = "d94b90a5-e9fd-4997-9920-13c283683634"
license = "Elastic License v2"
name = "Reflective Dylib Load"
os_list = ["macos"]
reference = [
    "https://github.com/MythicAgents/poseidon/tree/master/Payload_Type/poseidon/agent_code/execute_memory",
    "https://github.com/slyd0g/SwiftInMemoryLoading",
    "https://github.com/xpn/DyldDeNeuralyzer/tree/main",
]
version = "1.0.27"

query = '''
library where ((event.action == "load" and not dll.path : "?*") or 
  (event.action == "load" and dll.name : "NSCreateObjectFileImageFromMemory*")) and 
  not process.code_signature.subject_name : ("Developer ID Application: AMZN Mobile LLC (94KV3E626L)",
                                             "Apple Mac OS Application Signing") and 
  not (process.name : ("osx-x86_64", 
                       "Setup",
                       "oahd-helper",
                       "Dolby Atmos Renderer",
                       "ARCHICAD",
                       "ArtPro",
                       "oahd",
                       "pluginrunner",
                       "Install") and 
       process.code_signature.trusted == true) and 
  not Effective_process.executable : ("/Applications/Monotype desktop app/Monotype desktop app.app/Contents/MacOS/masMonitor",
                                      "/Applications/Amazon Music.app/Contents/MacOS/Amazon Music",
                                      "/Applications/GRAPHISOFT/ARCHICAD 24/ARCHICAD 24.app/Contents/MacOS/ARCHICAD",
                                      "/Applications/SoundFlow.app/Contents/Helpers/SoundFlow.app/Contents/MacOS/sfbackend",
                                      "/Applications/iZotope Product Portal.app/Contents/MacOS/Product Portal") and
  not process.executable : ("/System/*", 
                            "/Library/Application Support/Native Instruments/Komplete Kontrol/ScanApp3.app/Contents/MacOS/ScanApp3",
                            "/Applications/Logic Pro X.app/Contents/MacOS/Logic Pro X",
                            "/Applications/Avid/AvidAudioServer/AvidAudioServer.app/Contents/MacOS/AvidAudioServer",
                            "/Applications/Ableton Live * Lite.app/Contents/App-Resources/Extensions/PluginScanner/Ableton Plugin Scanner",
                            "/Applications/Pro Tools.app/Contents/MacOS/Pro Tools",
                            "/Applications/Ableton Live * Lite.app/Contents/MacOS/Live",
                            "/Applications/Reason 12.app/Contents/MacOS/Reason",
                            "/Applications/Ableton Live * Suite.app/Contents/MacOS/Live",
                            "/Applications/Reason 12.app/Contents/MacOS/PlugInspector",
                            "/Applications/Avid Media Composer/AvidMediaComposer.app/Contents/MacOS/AvidMediaComposer",
                            "/Library/Application Support/Native Instruments/Maschine 2/ScanApp.app/Contents/MacOS/ScanApp",
                            "/Applications/REAPER.app/Contents/MacOS/REAPER",
                            "/Applications/Neural DSP/*",
                            "/Library/Application Support/Native Instruments/Komplete Kontrol/ScanApp.app/Contents/MacOS/ScanApp",
                            "/Applications/TouchDesigner.app/Contents/MacOS/TouchDesigner",
                            "/Applications/Ableton Live 11 Suite.app/Contents/MacOS/Live",
                            "/Applications/Ableton Live 11 Suite.app/Contents/App-Resources/Extensions/PluginScanner/Ableton Plugin Scanner")
'''

min_endpoint_version = "8.11.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1106"
name = "Native API"
reference = "https://attack.mitre.org/techniques/T1106/"


[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1620"
name = "Reflective Code Loading"
reference = "https://attack.mitre.org/techniques/T1620/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.11.0"
