[rule]
description = """
Identifies suspicious instances of the Windows Error Reporting process (WerFault.exe or Wermgr.exe) with matching a
suspicious parent call stack. This may be indicative of a masquerading attempt to evade suspicious child process
behavior detections.
"""
id = "ace0bb76-290f-4f5f-a21f-c3b13ee415a9"
license = "Elastic License v2"
name = "Potential Masquerading as Windows Error Manager"
os_list = ["windows"]
version = "1.0.24"

query = '''
process where event.action == "start" and
 process.name : ("WerFault.exe", "wermgr.exe", "WerFaultSecure.exe") and
 process.parent.thread.Ext.call_stack_summary : "*|*" and
 not process.parent.thread.Ext.call_stack_summary : ("*faultrep.dll*", "*wersvc.dll*", "*|wer.dll|*", "*|ubpm.dll|*", "*|cbscore.dll|rpcrt4.dll*") and
 not _arraysearch(process.parent.thread.Ext.call_stack, $entry,
                  $entry.symbol_info: ("*kernel32.dll*!Wer*",
                                       "*KernelBase.dll*!UnhandledExceptionFilter*",
                                       "*kernel32.dll*!BasepReportFault*",
                                       "*combase.dll!CoSetErrorInfo*",
                                       "?:\\Program Files\\*.dll*", 
                                       "?:\\Program Files (x86)\\*.dll*",
                                       "?:\\Windows\\System32\\dataclen.dll*Purge*",
                                       "?:\\Windows\\WinSxS\\Temp\\PendingDeletes\\*!WerpLaunchAeDebug*",
                                       "?:\\Windows\\System32\\tmumh\\*.dll*",
                                       "*kernel32.dll*!WerpLaunchAeDebug*",
                                       "?:\\Windows\\System32\\SettingsHandlers_StorageSense.dll!GetSettingForUser*",
                                       "?:\\Windows\\WinSxS\\Temp\\PendingDeletes\\*!UbpmTriggerConsumerQueryStatus*",
                                       "?:\\Windows\\System32\\SettingsHandlers_StorageSense.dll!DllGetActivationFactory*",
                                       "?:\\Windows\\System32\\dataclen.dll!DllCanUnloadNow+*", 
                                       "?:\\Windows\\System32\\CsXumd64_*.dll+*", 
                                       "*Acrobat.exe!IsSandboxedProcess*", 
                                       "*AcroRd32.exe!IsSandboxedProcess*", 
                                       "C:\\Temp\\tmmon64.dll+*", 
                                       "*\\PendingDeletes\\$$DeleteMe*", 
                                       "*ntdll.dll+0*", 
                                       "*KernelBase.dll+0x*",
                                       "*ntdll.dll!RtlCreateProcessReflection*", 
                                       "*ntdll.dll!RtlInitializeExceptionChain*", 
                                       "*dataclen.dll!?Purge*", 
                                       "*dataclen.dll!DllCanUnloadNow*", 
                                       "*shell32.dll!AssocCreateForClasses*")) and
 not process.parent.thread.Ext.call_stack_summary : "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|wow64win.dll|ntdll.dll" and 
 not _arraysearch(process.parent.thread.Ext.call_stack, $entry, $entry.callsite_trailing_bytes : "488945???88b4d*") and
 not _arraysearch(process.parent.thread.Ext.call_stack, $entry,
                  $entry.callsite_trailing_bytes : "48894550488b4508488b4d5048894810488b4500ff5040488b4d088901488b8580000000488b40304889454048837d40000f84b5000000488b45008b08488b45")
'''

min_endpoint_version = "8.8.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1036"
name = "Masquerading"
reference = "https://attack.mitre.org/techniques/T1036/"

[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.8.0"
