[rule]
description = """
Identifies attempts to manipulate a remote process memory via allocating a RWX memory region or changing memory
permissions and by a process running from an unusual location, unsigned or executed remotely. This may indicate an
attempt to inject code into a remote process.
"""
id = "902f471c-27b4-4e78-b344-be46c6cfb72b"
license = "Elastic License v2"
name = "Remote Process Manipulation by Suspicious Process"
os_list = ["windows"]
version = "1.0.15"

query = '''
sequence by process.entity_id
 [process where event.action == "start" and
  (
   (process.Ext.device.product_id : ("Virtual DVD-ROM", "Virtual Disk", "USB *") and
    not process.executable : "C:\\*") or

    process.Ext.session_info.logon_type == "Network" or

   ((process.Ext.relative_file_creation_time <= 900 or process.Ext.relative_file_name_modify_time <= 900) and
     not process.code_signature.status : ("trusted", "errorExpired", "errorCode_endpoint*")) or

   process.executable :
	        ("?:\\Users\\*\\AppData\\*",
	         "?:\\Users\\*\\Downloads\\*",
	         "?:\\Users\\*\\Desktop\\*",
	         "?:\\Users\\Public\\*",
	         "?:\\ProgramData\\*") or

   process.name : ("powershell.exe", "wscript.exe", "cscript.exe", "rundll32.exe", "winword.exe", "excel.exe",
                  "powerpnt.exe", "msiexec.exe")
   ) and
   not (process.executable : "?:\\Users\\*\\AppData\\*" and process.code_signature.status : "trusted") and
   not (process.name : "rundll32.exe" and
        process.parent.executable : ("?:\\Program Files (x86)\\Kaarya LLC\\myKaarma Desktop\\KaarmaDesktop.exe",
                                     "?:\\Program Files (x86)\\Quicken\\qw.exe",
                                     "?:\\Program Files (x86)\\VisualCron\\VisualCronClient.exe",
                                     "?:\\Program Files (x86)\\Kaarya LLC\\Kaarma Desktop\\KaarmaDesktop.exe")) and
   not (process.name : "rundll32.exe" and process.args : "?:\\WINDOWS\\system32\\inetcpl.cpl,ClearMyTracksByProcess" and
        process.parent.executable : "?:\\Program Files*\\Internet Explorer\\iexplore.exe") and
   not (process.name : "rundll32.exe" and process.parent.executable : "?:\\Users\\*\\AppData\\Local\\Temp\\SNXAC\\STAProxy.exe" and
        process.args : "?:\\Users\\*\\AppData\\Local\\Temp\\snxac\\*\\sta.dll,LaunchSTA") and
   not (process.name : "rundll32.exe" and process.command_line : "*--enable-speech-input*--enable-media-stream*")
  ]
 [api where process.Ext.api.behaviors : "cross-process" and
  process.Ext.api.name : ("VirtualAllocEx", "VirtualProtectEx") and
  (
   process.Ext.api.parameters.protection == "RWX" or
   process.Ext.api.parameters.protection_old == "RWX" or
   (process.Ext.api.parameters.protection : "*X*" and process.Ext.api.parameters.protection_old : "*W*")
   ) and
   not process.Ext.api.parameters.size <= 4096 and 
   process.thread.Ext.call_stack_summary : "?*" and not user.id : ("S-1-5-19", "S-1-5-20") and 
   not (process.executable : ("?:\\Program Files\\*.exe", "?:\\Program Files (x86)\\*.exe", "?:\\Windows\\*") and
        process.code_signature.trusted == true and not process.code_signature.subject_name : "Microsoft*") and
   not (process.Ext.api.summary : "*splwow64.exe*" and process.name : "msiexec.exe" and
        process.thread.Ext.call_stack_summary : "*ntdll.dll|kernelbase.dll|winspool.drv|*") and
   not _arraysearch(process.thread.Ext.call_stack, $entry,
                   $entry.symbol_info : ("?:\\Program Files\\*.dll*", 
                                         "?:\\Program Files (x86)\\*.dll*", 
                                         "?:\\windows\\system32\\*\\tmmon*.dll*", 
					 "?:\\windows\\syswow64\\*\\tmmon*.dll*", 
                                         "?:\\Windows\\SysWOW64\\esensordbi.dll*", 
                                         "?:\\Windows\\System32\\esensordbi.dll*", 
                                         "?:\\Windows\\System32\\umppc*.dll*",
					  "?:\\Windows\\SysWOW64\\umppc*.dll*",
                                         "?:\\Windows\\FireEye\\AppMonitorDll*.dll*", 
                                         "?:\\Windows\\apppatch\\AppPatch*\\exploitblocker.dll*", 
                                         "?:\\windows\\system32\\hmpalert.dll*",
					 "?:\\windows\\syswow64\\hmpalert.dll!*")) and 
   not _arraysearch(process.thread.Ext.call_stack, $entry, 
                    $entry.protection_provenance : ("Kernel*", "appvisvsubsystems64.dll", "*appvisvsubsystems.dll*", 
		                                    "*appventsubsystems32.dll*", "*appventsubsystems64.dll*", "*appventsubsystems.dll*")) and
   not process.thread.Ext.call_stack_final_user_module.name == "Kernel" and
   /* Cynet MemScanner, xSecuritas, Mcafee */
   not _arraysearch(process.thread.Ext.call_stack, $entry,
                    $entry.callsite_trailing_bytes :
                         ("48898424e80300004883bc24e803000000750eff94247e030000898424f0030000eb30488d8c2430010000ff94248e03000048898424e80300004883bc24e803",
                          "8bd885db751eff55c88945f8eb168d8592fdffff50ff55d08bd885db7506ff55c88945f856ff55bc85db0f847601000080bd82fcffff0074508b45fc05a00000",
                          "488b55a8c6420c01833d8bbeb25f007406ff1593c7b25f8945b4488bcce82c000000908b45b4488b55a8c6420c01488b55a8488b8d70ffffff48894a10488d65", 
                          "2048894538488b4d1048c1e103488b7d38488b7550f3a44c8b4d284d8b49484c8b45284d8b4040488b5528488b5220488b4d28488b8988000000ff95a0000000"))

   ]
  until [process where event.action:"end"]
'''

min_endpoint_version = "8.10.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0
tree = true

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
