[rule]
description = """
Identifies attempts to load a library from a memory section with read, write and execute permissions and backed by a
file. This may indicate image hollowing or unpacking from suspicious memory sections.
"""
id = "a1d00ee9-64d6-440a-8940-fd2d940152a6"
license = "Elastic License v2"
name = "Network Module Loaded from a Backed RWX Memory"
os_list = ["windows"]
version = "1.0.11"

query = '''
sequence by process.entity_id with maxspan=1m
 [process where event.action == "start" and
  (
   (process.Ext.device.product_id : ("Virtual DVD-ROM", "Virtual Disk", "USB *") and
    not process.Ext.device.nt_name: "\\Device\\HarddiskVolume*" and not process.Ext.device.vendor_id == "Citrix") or

   process.name : ("rundll32.exe", "regsvr32.exe", "msiexec.exe") or

   (process.executable : ("?:\\Users\\*", "?:\\ProgramData\\*") and process.Ext.relative_file_creation_time <= 500 and
    not process.code_signature.status : ("trusted", "errorExpired", "errorCode_endpoint*"))
   ) and
  not process.hash.sha256 :
                ("a6061528b62fb3e57ecf48db7d9f760d7df3298aad6fe0231a1a97a5619490b7",
                 "edd35332ab97e86f70132ffa9d8e9cb47d79f12c3c50bf4eb5cf6de55c214d47",
                 "b3f9c9d24914fb770551c6e8563cf93844f31630583a8fec2a529bc785284b92")

  ]
 [library where dll.name : ("ws2_32.dll", "winhttp.dll", "wininet.dll") and
  not process.thread.Ext.call_stack_contains_unbacked == true and
  process.thread.Ext.call_stack_summary : "?*" and
  not process.thread.Ext.call_stack_summary : ("*Unbacked*", "*clr.dll*", "*Unknown*") and
  _arraysearch(process.thread.Ext.call_stack, $entry, $entry.protection : "RWX" and $entry.callsite_trailing_bytes : "?*" and $entry.allocation_private_bytes >= 100000) and
  not _arraysearch(process.thread.Ext.call_stack, $entry,
	                $entry.protection : "RWX" and
	                $entry.symbol_info : ("?:\\Windows\\Temp\\*", "?:\\Windows\\Installer\\*", "?:\\Users\\*\\AppData\\Local\\Temp\\MSI*.tmp*",
	                                      "?:\\Windows\\System32\\*", "?:\\Windows\\Syswow64\\*", "?:\\Program Files*", "*isrt.dll!_InitInstall*",
	                                      "*ISSetup.dll!DllUnregisterServer*", "?:\\Users\\*\\AppData\\Local\\Temp\\nsm????.tmp*")) and
  not (process.name : "msiexec.exe" and process.thread.Ext.call_stack_summary : "*|isrt.dll|*") and
  not process.thread.Ext.call_stack_summary :("*|msi.dll|issetup.dll|*", "*|isrt.dll|issetup.dll|isrt.dll|*", "*|isrt.dll|issetup.dll|*") and
  not process.thread.Ext.call_stack_summary : ("*ntdll.dll|kernelbase.dll|issetup.dll|*", "*ntdll.dll|kernelbase.dll|irsetup.exe*") and
  not _arraysearch(process.thread.Ext.call_stack, $entry,
                   $entry.callsite_trailing_bytes : ("*488b004885c0741d4889542438b903000000ffd0488b5424384885c04989c6*",
                                                     "8bf885ff754eff15*8945ec85ff74168d45cc8bcf506a03ff15*",
                                                     "83c60483fe7072f08d851cfdffffc7851cfd*",
                                                     "8b55ec8bf083fa1072288b4*",
                                                     "894310837b1000750c8bc3e8ee04*", 
						     "8b55cc89028b151c40420085d2740e8b02ff750c6a0152ff500883c40c8b55cc*",
						     "8bd88b4424388b0885db0f85ff00000085c9741783f9ff741f83c9fff00fc1080f95c084*"))
 ]
'''

min_endpoint_version = "8.8.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.8.0"
