[rule]
description = """
Identifies attempts to call a memory management API from a thread that was previously in a sleep state. This may
indicate an attempt to evade detection via time based evasion techniques.
"""
id = "47aec49c-4f8b-4245-8eae-7d615f30f154"
license = "Elastic License v2"
name = "Potential Evasion via Sleep Obfuscation"
os_list = ["windows"]
version = "1.0.13"

query = '''
api where
 process.Ext.api.name == "VirtualProtect" and process.Ext.api.behaviors == "execute_fluctuation" and
 process.thread.Ext.call_stack_final_user_module.name == "ntdll.dll" and
  _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info: ("*ntdll.dll!ZwProtectVirtualMemory*", "*ntdll.dll!NtProtectVirtualMemory*")) and
 _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info: ("*ntdll.dll!ZwDelayExecution*", "*ntdll.dll!NtDelayExecution*")) and 
 _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info: "*kernelbase.dll!SleepEx*") and
 _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info: "*ntdll.dll!KiUserApcDispatcher*")
'''

min_endpoint_version = "8.10.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"

[[threat.technique]]
id = "T1497"
name = "Virtualization/Sandbox Evasion"
reference = "https://attack.mitre.org/techniques/T1497/"
[[threat.technique.subtechnique]]
id = "T1497.003"
name = "Time Based Evasion"
reference = "https://attack.mitre.org/techniques/T1497/003/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
