[rule]
description = "Identifies attempts to prevent a debugger from attaching to a process via patching the NTDLL module debugging functions."
id = "4db10fd9-e219-4566-9388-8e9a0b7ac7a9"
license = "Elastic License v2"
name = "Process Anti-Debug via Memory Patching"
os_list = ["windows"]
reference = [
    "https://anti-debug.checkpoint.com/techniques/process-memory.html#patch_ntdll_dbguiremotebreakin",
    "https://anti-debug.checkpoint.com/techniques/process-memory.html#patch_ntdll_dbgbreakpoint",
]
version = "1.0.3"

query = '''
api where process.Ext.api.name : "WriteProcessMemory" and
 process.Ext.api.summary : ("*DbgUiRemoteBreakin*", "*DbgBreakPoint*") and
 process.thread.Ext.call_stack_final_user_module.name != null and
 not (process.code_signature.status : "trusted" and
      process.code_signature.subject_name : ("UBISOFT ENTERTAINMENT INC.", "BattlEye Innovations e.K.", "KOBIL GmbH",
      "Epic Games Inc.", "M.E.DOC LLC", "BOHEMIA INTERACTIVE a.s.", "MetaQuotes Ltd", "Bandicam Company Corp.",
      "BATTLESTATE GAMES LIMITED", "Ubisoft Entertainment Sweden AB", "Star Finanz - Software Entwicklung und Vertriebs GmbH",
      "Environmental Systems Research Institute, Inc.", "miHoYo Co.,Ltd.", "HP Tuners LLC", "COGNOSPHERE PTE. LTD.",
      "SZ DJI Technology Co., Ltd.", "Star Finanz-Software Entwicklung und Vertriebs GmbH")) and
 not process.executable : ("?:\\Program Files (x86)\\*.exe", "?:\\Program Files\\*.exe") and
  not process.thread.Ext.call_stack_final_user_module.name : ("Kernel", "Unknown") and
  not (process.code_signature.status : "trusted" and startswith~(process.thread.Ext.call_stack_final_user_module.name, process.name)) and
  not process.thread.Ext.call_stack_final_user_module.path :
                              ("?:\\Program Files\\*",
                               "?:\\Program Files (x86)\\*",
                               "\\Program Files\\*",
                               "\\Program Files (x86)\\*",
                               "?:\\windows\\system32\\*",
                               "?:\\windows\\syswow64\\*",
                               "?:\\windows\\assembly\\*",
                               "?:\\Windows\\FireEye\\AppMonitorDll*.dll*",
                               "?:\\Windows\\apppatch\\AppPatch*\\exploitblocker.dll*") and
  not process.thread.Ext.call_stack_final_user_module.hash.sha256 :
                         ("2a9b218ef8897b17ea485d41be9d8145ece535e8f14f44de84ea97048399f5a4",
                          "b98f6fffd39455ebb8a480be09fc020f26a2d9ce14901a39886a3c367e4dc3fe",
                          "fd55b535a38bec99a9e4eec910b5ac032ca29dbf94ca16c344c3006d77404b41")
'''

min_endpoint_version = "8.10.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1574"
name = "Hijack Execution Flow"
reference = "https://attack.mitre.org/techniques/T1574/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
