[rule]
description = """
Identifies calls to Windows memory APIs from unusual modules or NTDLL offsets. This may indicate an attempt to bypass
API monitoring using Return Oriented Programming (ROP) assembly gadgets to execute a syscall instruction.
"""
id = "d7239b58-3e32-481a-9bfa-63e04caf1a4e"
license = "Elastic License v2"
name = "Suspicious Windows API Call via ROP Gadgets"
os_list = ["windows"]
version = "1.0.18"

query = '''
sequence by process.entity_id with maxspan=1m
[library where 
  ((dll.Ext.relative_file_creation_time <= 300 or
    (dll.Ext.device.product_id : ("Virtual DVD-ROM", "Virtual Disk") and not dll.path : "C:\\*")) and
   (dll.code_signature.trusted == false or dll.code_signature.exists == false))] as event0
[api where 

 process.Ext.api.name : ("VirtualAlloc*", "VirtualProtect*", "MapViewOfFile*") and process.executable != null and

 process.thread.Ext.call_stack_summary :("ntdll.dll|*", "win32*", "kernel*") and 

 startswith~(process.thread.Ext.call_stack_final_user_module.name, event0.dll.name) and 

 not process.thread.Ext.call_stack_final_user_module.name : "Kernel" and process.thread.Ext.call_stack_final_user_module.path != null and 
 
 not process.thread.Ext.call_stack_final_user_module.path : 
                         ("?:\\Program Files\\*", 
                          "?:\\Program Files (x86)\\*", 
                          "\\Program Files*",
                          "?:\\Windows\\Microsoft.NET\\Framework*", 
                          "\\Windows\\Microsoft.NET\\Framework*", 
                          "?:\\windows\\system32\\*", 
                          "\\windows\\system32\\*", 
                          "?:\\windows\\syswow64\\*", 
                          "\\windows\\syswow64\\*", 
                          "?:\\windows\\winsxs\\*", 
                          "\\windows\\winsxs\\*", 
                          "?:\\Windows\\assembly\\*", 
                          "\\Windows\\assembly\\*", 
                          "?:\\windows\\system32\\hmpalert.dll",
                          "c:\\cyberdigm\\destinydrive\\pantansx64.dll",
                          "c:\\cyberdigm\\destinydrive\\pantasec64.dll",
                          "?:\\users\\*\\appdata\\local\\microsoft\\teams\\current\\teams.exe", 
                          "\\users\\*\\appdata\\local\\microsoft\\teams\\current\\teams.exe", 
                          "?:\\users\\*\\appdata\\local\\slack\\app-*\\slack.exe", 
                          "?:\\users\\*\\appdata\\local\\programs\\signal-desktop\\signal.exe", 
                          "?:\\users\\*\\appdata\\local\\programs\\burpsuitepro\\jre\\bin\\server\\jvm.dll") and 

 not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info:
                                                                 ("*ntdll.dll!*ProtectVirtualMemory*",
                                                                  "*ntdll.dll!*MapViewOfSection*",
                                                                  "*ntdll.dll!*AllocateVirtualMemory*",
                                                                  "*ntdll.dll!*CreateUserProcess*",
                                                                  "*ntdll.dll!*CreateProcess*",
                                                                  "*ntdll.dll!*DeviceIoControlFile*",
                                                                  "*ntdll.dll!*AssignProcessToJobObject*",
                                                                  "*ntdll.dll!ZwQuerySystemInformation*",
                                                                  "*ntdll.dll!*CreateThread*",
                                                                  "*kernelbase.dll!SetProcessDynamicEnforcedCetCompatibleRanges*",
                                                                  "*ntdll.dll!RtlCaptureContext*",
                                                                  "*kernelbase.dll!VirtualProtect*",
                                                                  "*ntdll.dll!LdrShutdownProcess*",
                                                                  "*ntdll.dll!NtdllDialogWndProc_W*",
                                                                  "*ntdll.dll!*WriteRequestData*",
                                                                  "*ntdll.dll!KiUserInvertedFunctionTable*",
                                                                  "*ntdll.dll!*DeleteAtom*", 
                                                                  "*ntdll.dll!*QuerySection*", 
                                                                  "*ntdll.dll!*TerminateThread*",
                                                                  "*kernelbase.dll*!CreateProcess*", 
                                                                  "*ntdll.dll*!*AlpcOpenSenderProcess*", 
                                                                  "*ntdll.dll*!*AlpcCreateResourceReserve*",
                                                                  "ntdll.dll*!*IsProcessInJob*",
                                                                  "*ntdll.dll*!*SetInformationFile*",
                                                                  "*ntdll.dll*!NtSetEvent*",
                                                                  "*ntdll.dll*!RtlGetNativeSystemInformation*",
                                                                  "*ntdll.dll*!KiUserApcDispatcher*",
                                                                  "*ntdll.dll!LdrLoadDll*",
                                                                  "*ntdll.dll*!NtReadRequestData*",
                                                                  "*ntdll.dll!RtlVirtualUnwind*",
                                                                  "\\device\\+0*",
                                                                  "*ntdll.dll+0x*",
                                                                  "*ntdll.dll*!*CreateLowBoxToken*",
                                                                  "*kernelbase.dll!DeviceIoControl*",
                                                                  "*ntdll.dll!KiRaiseUserExceptionDispatcher*",
                                                                  "*ntdll.dll!*IsProcessInJob*",
                                                                  "*ntdll.dll!*PowerInformation*")) and

 not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info : "*ntdll.dll*" and $entry.allocation_private_bytes > 0) and

 not (process.code_signature.subject_name == "Activision Publishing Inc" and process.code_signature.trusted == true and 
      process.executable : "?:\\Program Files (x86)\\Call of Duty\\_retail_\\*.exe") and

 not (process.thread.Ext.call_stack_summary : "ntdll.dll|Unknown|ntdll.dll*" and
      _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info : "*ntdll.dll!*TestAlert*")) and

 not _arraysearch(process.thread.Ext.call_stack, $entry,
                     $entry.symbol_info : ("?:\\windows\\system32\\sysfer.dll*",
                                           "?:\\Windows\\WinSxS\\*\\$$DeleteMentdll.dll*",
                                           "?:\\windows\\winsxs\\temp\\*\\$$deleteme.ntdll.dll*",
                                           "?:\\Program Files\\*.dll*",
                                           "?:\\Program Files (x86)\\*.dll*",
                                           "?:\\windows\\system32\\*\\tmmon*.dll*",
                                           "?:\\windows\\SysWOW64\\*\\tmmon*.dll*",
                                           "?:\\windows\\system32\\tmumh\\*\\tmmon*.dll*",
                                           "?:\\Windows\\SysWOW64\\esensordbi.dll*",
                                           "?:\\Windows\\System32\\esensordbi.dll*",
                                           "?:\\Windows\\System32\\umppc*.dll*",
                                           "?:\\Windows\\SysWOW64\\umppc*.dll*",
                                           "?:\\Windows\\FireEye\\AppMonitorDll*.dll*",
                                           "?:\\Windows\\apppatch\\AppPatch*\\exploitblocker.dll*",
                                           "?:\\windows\\system32\\hmpalert.dll!*",
                                           "?:\\windows\\SysWOW64\\hmpalert.dll!*",
                                           "?:\\programdata\\microsoft\\windows defender\\definition updates\\*\\mpengine.dll*")) and

 not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.protection_provenance : "?*" and $entry.symbol_info : "*ntdll.dll+0x*") and

 not (process.code_signature.trusted == true and process.executable : ("?:\\Program Files (x86)\\*.exe", "?:\\Program Files\\*.exe") and
      not process.code_signature.subject_name : "Microsoft *") and
 not (process.executable : "?:\\Windows\\System32\\sppsvc.exe" and process.parent.executable : "?:\\Windows\\System32\\services.exe")]
'''

min_endpoint_version = "8.10.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
