[rule]
description = """
Identifies a Windows script interpreter executing for more than 5 minutes followed by spawning a child process. This may
indicate long term network activity from a Windows script which is common pattern of a command and control backdoor via
malicious scripts.
"""
id = "c89c8742-9040-4de8-b3cf-477407fafac1"
license = "Elastic License v2"
name = "Suspicious Execution from a Windows Script"
os_list = ["windows"]
version = "1.0.10"

query = '''
sequence with maxspan=1m
 [network where process.uptime >= 300 and
  process.name : ("cscript.exe", "wscript.exe", "AutoIt*.exe")] by process.entity_id
 [process where event.action == "start" and
  process.parent.name : ("cscript.exe", "wscript.exe", "AutoIt*.exe") and
  not process.hash.sha256 :
                  ("ab4ebfc23f71658cc30d21d53a5d774eba2bc27cf5806aafd18f263590541b89",
                   "42bb9150cf428aa3ea2ab4d9d27d30072a7af1ee8c00fd735ef90c11d29e96d6") and
  not (process.name : "reg.exe" and process.args : "HKLM\\SOFTWARE\\AutoTools\\ADP SmartAgent\\SmartAgent\\Jobs" and user.id : "S-1-5-18") and
  not process.parent.args :
              ("?:\\Program Files (x86)\\smartagent\\agent\\common\\snapins\\adpcommon\\ADP_*.vbs",
               "?:\\\\Program Files (x86)\\\\Tanium\\\\Tanium Client\\\\Patch\\\\lib\\\\tanium-patch.min.vbs")] by process.parent.entity_id
'''

min_endpoint_version = "8.8.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.007"
name = "JavaScript"
reference = "https://attack.mitre.org/techniques/T1059/007/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1071"
name = "Application Layer Protocol"
reference = "https://attack.mitre.org/techniques/T1071/"

[[threat.technique]]
id = "T1573"
name = "Encrypted Channel"
reference = "https://attack.mitre.org/techniques/T1573/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "8.8.0"
