[rule]
description = """
Detects the creation of a reverse shell through a suspicious process chain spawned via a utility with suspicious command
line arguments. Reverse shells spawned by the specified utilities that are initialized from a single process followed by
a network connection attempt will be captured through this rule. Attackers may spawn reverse shells to establish
persistence onto a target system.
"""
id = "c71b9783-ca42-4532-8eb3-e8f2fe32ff39"
license = "Elastic License v2"
name = "Linux Reverse Shell via Suspicious Utility"
os_list = ["linux"]
version = "1.0.3"

query = '''
sequence by process.entity_id with maxspan=1s
  [process where event.type == "start" and event.action in ("fork", "exec") and (
    (process.name : "python*" and process.args : "-c" and process.args : (
     "*import*pty*spawn*", "*import*subprocess*call*"
    )) or
    (process.name : "perl*" and process.args : "-e" and process.args : "*socket*" and process.args : (
     "*exec*", "*system*"
    )) or
    (process.name : "ruby*" and process.args : ("-e", "-rsocket") and process.args : (
     "*TCPSocket.new*", "*TCPSocket.open*"
     )) or
    (process.name : "lua*" and process.args : "-e" and process.args : "*socket.tcp*" and process.args : (
     "*io.popen*", "*os.execute*"
    )) or
    (process.name : "php*" and process.args : "-r" and process.args : "*fsockopen*" and process.args : "*/bin/*sh*") or 
    (process.name : ("awk", "gawk", "mawk", "nawk") and process.args : "*/inet/tcp/*")
   )]
  [network where event.type == "start" and event.action in ("connection_attempted", "connection_accepted") and 
   process.name : ("python*", "php*", "perl", "ruby", "lua*", "*awk") and destination.ip != null and not cidrmatch(
     destination.ip, "127.0.0.0/8", "169.254.0.0/16", "224.0.0.0/4", "::1"
   )]
'''

min_endpoint_version = "8.5.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.004"
name = "Unix Shell"
reference = "https://attack.mitre.org/techniques/T1059/004/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1071"
name = "Application Layer Protocol"
reference = "https://attack.mitre.org/techniques/T1071/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "8.5.0"
