[rule]
description = """
Detects process events where the process is Powershell (pwsh) or a shell interpreter (sh, bash, zsh) with the encoded
command flag set in the process arguments. Powershell usage on macOS is extremely rare but usage of Powershell with the
encoded command flag, used for executing base64 encoded command strings, is almost always inherently malicous.
"""
id = "4abb4f46-2066-4769-b073-dca491067e1b"
license = "Elastic License v2"
name = "Powershell Encoded Command"
os_list = ["macos"]
version = "1.0.12"

query = '''
process where event.type == "start" and process.args : ("-EncodedCommand", "-enc") and
 process.name : ("sh", "bash", "zsh", "pwsh") and
 not process.args : "/Applications/Visual Studio Code.app/*" and 
 not process.executable : "/Applications/Docker.app/Contents/Resources/bin/docker" and
 not process.parent.executable : ("/Applications/Docker.app/Contents/Resources/bin/com.docker.cli", 
                                  "/Applications/Docker.app/Contents/Resources/bin/docker") and
 not process.Ext.effective_parent.name : "electron" and
 not ((process.name : "zsh" and process.parent.name : "zsh") or
      (process.name : "pwsh" and process.parent.name : "pwsh") or
      (process.name : "pwsh" and process.parent.name : "Code Helper"))
'''

min_endpoint_version = "8.7.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.001"
name = "PowerShell"
reference = "https://attack.mitre.org/techniques/T1059/001/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"

[internal]
min_endpoint_version = "8.7.0"
