[rule]
description = """
Identifies the execution of commonly abused native binaries or processes from unusual paths and from a remote network
logon session. This may indicate lateral movement via remote services.
"""
id = "706cc79a-f227-43ae-a3aa-8b6461f8eddc"
license = "Elastic License v2"
name = "Suspicious Process Execution via Network Logon"
os_list = ["windows"]
version = "1.0.38"

query = '''
process where event.action == "start" and
 process.Ext.session_info.logon_type == "Network" and
 process.Ext.session_info.relative_logon_time <= 5 and process.executable : "C:\\*" and
 (
  process.name : ("powershell.exe", "cmd.exe", "rundll32.exe", "regsvr32.exe", "regasm.exe", "mshta.exe",
                  "wscript.exe", "msbuild.exe", "installutil.exe", "bash.exe", "excel.exe", "winword.exe", "mshta.exe") or
  process.parent.name : "mmc.exe" or
  (process.parent.name : "svchost.exe" and process.parent.args : "DcomLaunch") or
  process.parent.args : "-Embedding" or
  process.executable :
           ("?:\\Windows\\Microsoft.NET\\*",
            "?:\\Users\\Public\\*",
            "?:\\ProgramData\\*",
            "?:\\Windows\\Tasks\\*",
            "?:\\Users\\*\\AppData\\Roaming\\*",
            "?:\\Windows\\System32\\Tasks\\*",
            "?:\\PerfLogs\\*",
            "?:\\Users\\Default\\*",
            "?:\\Windows\\Logs\\*",
            "?:\\windows\\Help\\*",
            "?:\\Windows\\INF\\*",
            "*:\\Users\\*\\Music\\*",
            "*:\\Users\\*\\Pictures\\*")
  ) and

  not process.executable :
             ("?:\\Windows\\System32\\wsmprovhost.exe",
              "?:\\Windows\\syswow64\\wsmprovhost.exe",
              "?:\\Windows\\System32\\conhost.exe",
              "?:\\Windows\\System32\\winrshost.exe",
              "?:\\Windows\\Microsoft.NET\\Framework*\\csc.exe",
              "?:\\Windows\\Microsoft.NET\\Framework*\\cvtres.exe",
              "?:\\Windows\\System32\\w32tm.exe",
              "?:\\Windows\\System32\\netsh.exe",
              "?:\\Windows\\System32\\msiexec.exe",
              "?:\\Program Files (x86)\\Kaspersky Lab\\NetworkAgent\\klnagchk.exe",
              "?:\\Program Files (x86)\\Flexx\\Sistemas\\flgacesso.exe",
              "?:\\Program Files\\7-Zip\\7z.exe",
              "?:\\Windows\\System32\\plasrv.exe",
              "?:\\Windows\\System32\\vdsldr.exe",
              "?:\\Windows\\System32\\gpupdate.exe",
              "?:\\ProgramData\\Microsoft Azure Site Recovery\\Mobility Service\\*.exe",
              "?:\\Windows\\System32\\WerFault.exe",
              "?:\\Windows\\System32\\dfsfrsHost.exe",
              "?:\\Windows\\System32\\wuauclt.exe",
              "?:\\Windows\\system32\\UsoClient.exe",
              "?:\\Windows\\system32\\findstr.exe",
              "?:\\Windows\\ccmsetup\\ccmsetup.exe",
              "?:\\Windows\\system32\\klist.exe",
              "?:\\Windows\\system32\\dnscmd.exe",
              "?:\\Windows\\System32\\chcp.com",
              "?:\\Windows\\System32\\manage-bde.exe",
              "?:\\Windows\\System32\\dllhost.exe",
              "?:\\Windows\\System32\\quser.exe",
              "?:\\Windows\\System32\\nslookup.exe",
              "?:\\Windows\\System32\\reg.exe",
              "?:\\Windows\\System32\\HOSTNAME.EXE",
              "?:\\Windows\\System32\\wbem\\WMIC.exe",
              "?:\\Windows\\System32\\NETSTAT.EXE",
              "?:\\Windows\\System32\\ipconfig.exe",
              "?:\\Windows\\System32\\shutdown.exe",
              "?:\\Windows\\System32\\net.exe",
              "?:\\Windows\\System32\\dsregcmd.exe",
              "?:\\Windows\\System32\\sc.exe",
              "?:\\Windows\\System32\\schtasks.exe",
              "?:\\Windows\\System32\\wbem\\WinMgmt.exe",
              "?:\\Windows\\System32\\OpenWith.exe",
              "?:\\Windows\\System32\\Dism.exe",
              "?:\\Windows\\System32\\query.exe",
              "?:\\Windows\\System32\\systeminfo.exe",
              "?:\\Windows\\System32\\auditpol.exe",
              "?:\\Windows\\System32\\HOSTNAME.EXE",
              "?:\\Windows\\System32\\PING.EXE",
              "?:\\Windows\\System32\\change.exe",
              "?:\\Windows\\System32\\PktMon.exe",
              "?:\\Windows\\System32\\whoami.exe",
              "?:\\Windows\\System32\\FcSrv.exe",
              "?:\\Program Files\\ansible\\GTS\\jre\\bin\\java.exe",
              "?:\\Windows\\system32\\ARP.EXE",
              "?:\\Windows\\system32\\tasklist.exe",
              "?:\\Windows\\System32\\dnscmd.exe",
              "?:\\Windows\\System32\\find.exe",
              "?:\\Windows\\System32\\findstr.exe",
              "?:\\Windows\\System32\\wermgr.exe",
              "?:\\Windows\\SysWOW64\\wermgr.exe",
              "?:\\Windows\\System32\\cscript.exe",
              "?:\\Windows\\System32\\takeown.exe",
              "?:\\Windows\\System32\\regini.exe",
              "?:\\WINDOWS\\system32\\iisreset.exe",
              "?:\\Windows\\System32\\SecEdit.exe",
              "?:\\Windows\\System32\\dsquery.exe",
              "?:\\Program Files (x86)\\Google\\Update\\*.exe",
              "?:\\Program Files\\Google\\Update\\*.exe",
              "?:\\Program Files\\Commvault\\installer\\Setup.exe",
              "?:\\Windows\\System32\\CPrepSrv.exe",
              "?:\\Windows\\System32\\repadmin.exe",
              "?:\\Windows\\System32\\dllhost.exe",
              "?:\\Windows\\SysWOW64\\dllhost.exe",
              "?:\\Windows\\System32\\inetsrv\\iisrstas.exe", 
              "?:\\Program Files\\ansible\\GTS\\uidext\\iam_iis_extract.exe", 
              "?:\\Windows\\System32\\bcdedit.exe", 
              "?:\\Windows\\System32\\dcdiag.exe",
              "?:\\Windows\\System32\\logman.exe",
              "?:\\Windows\\System32\\icacls.exe",
              "?:\\Windows\\System32\\regsvr32.exe",
              "?:\\Windows\\System32\\Robocopy.exe",
              "?:\\Windows\\System32\\wbem\\mofcomp.exe",
              "?:\\WINDOWS\\system32\\sfc.exe",
              "?:\\WINDOWS\\System32\\inetsrv\\iisrstas.exe",
              "?:\\Windows\\Microsoft.NET\\Framework*\\aspnet_regiis.exe", 
              "?:\\Program Files\\ansible\\GTS\\uidext\\iam_iis_extract.exe", 
              "?:\\Program Files\\Microsoft SQL Server\\*.exe", 
              "?:\\Program Files (x86)\\Microsoft SQL Server\\*.exe",
              "?:\\Windows\\System32\\msg.exe",
              "?:\\Windows\\System32\\wbadmin.exe",
              "?:\\Windows\\System32\\tzutil.exe",
              "?:\\Windows\\System32\\logoff.exe",
              "?:\\Windows\\System32\\powercfg.exe",
              "?:\\Windows\\System32\\winver.exe",
              "?:\\Windows\\System32\\cleanmgr.exe",
              "?:\\Windows\\System32\\CiTool.exe",
              "?:\\Windows\\System32\\gpresult.exe",
              "?:\\Windows\\System32\\inetsrv\\iisrstas.exe",
              "?:\\Windows\\WinSxS\\amd64_microsoft-windows-servicingstack_*\\TiFileFetcher.exe",
              "?:\\Program Files\\AzureConnectedMachineAgent\\azcmagent.exe",
              "?:\\Program Files\\WindowsApps\\Microsoft.DesktopAppInstaller_*\\winget.exe",
              "?:\\Windows\\System32\\DriverStore\\FileRepository\\*_x64PdsmqConnector.exe",
              "?:\\Program Files (x86)\\Emerson\\OpenEnterprise\\Bin\\OEOPCDAServer.exe") and

  not (process.name : ("cmd.exe", "powershell.exe") and
       /* limit powershell and cmd to download pattern, rest is pretty random and very noisy */
       not (process.command_line : ("*WebClient*", "*http*", "* -exec Bypass*", "* -enc *") and
            not process.command_line : 
                      ("*echo nessus_cmd*", "*$ErrorActionPreference*", "*-executionpolicy*"))) and

  not (process.executable : "?:\\Windows\\system32\\sc.exe" and process.args : ("config", "delete") and
       process.args : "VisualStudioRemoteDeployer*" and process.parent.name : "wsmprovhost.exe") and
  not (process.executable : "?:\\Windows\\System32\\net.exe" and process.args : ("stop", "start")) and
  not (process.name : ("cmd.exe", "powershell.exe") and
       process.command_line :
                   ("*Metadata*/metadata/instance/compute*",
                    "*metadata/latest/InstanceInfo*",
                    "*machine?comp=goalstate*",
                    "*Cloudamize_HOST_SHARE*", 
                    "*SrvNOW\\psscript_output_*", 
                    "*set site /site.name*",
                    "*netsh http show sslcert*",
                    "*/opc/v2/instance/*",
                    "*/latest/api/token*",
                    "*/latest/dynamic/instance-identity/document*", 
                    "*/opc/v2/instance/*", 
                    "*'X-aws-ec2-metadata-token-ttl-seconds*", 
                    "*/vmbackup/api/v?/hyperv/inventory/installer*", 
                    "*-api_ver vmbackup/api/*",
                    "*C:\\Windows\\temp\\ccpa-temp-*",
                    "*-client_name hyperv-*",
                    "*ccpa-temp*oval_registry*",
                    "*certstorename=MY*",
                    "*/latest/api/token*-TimeoutSec*",
                    "*\\program files (x86)\\citrix\\Licensing\\WebServicesForLicensing\\*",
                    "*JABQAHIAbwBnAHIAZQBzAHMAUAByAGUAZgBlAHIAZQBuAGMAZQA9ACIAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAiADsARwBlAHQALQBIAG8AdABmAGkAeAAgAHwAIABTAGUAbABlAGMAdAAtAE8AY*")) and
  not (process.name : "cmd.exe" and process.parent.name : "WmiPrvSe.exe" and
       process.args : (" > \\\\127.0.0.1\\c$\\temp\\gsa\\Production",
                       "} > \\\\127.0.0.1\\c$\\temp\\gsa\\Production",
                       "(x86)\\citrix\\Licensing\\WebServicesForLicensing\\Apache\\bin\\httpd.exe  -V  > \\\\127.0.0.1\\c$\\temp\\gsasandbox\\SandBox")) and
  not process.hash.sha256 :
                 ("06078b8b840b4591535566d18d5f88b201c4cb8e033361095f7fd37d058e6962",
                  "d57875f09a33cda2dc1030a4f82405f1de56b5536b6b87329323dfb2042b5e1c",
                  "603a70b53c4f9121081526723ea8a7cc29447d02899de7fd24d11ac7fdd42f8c",
                  "5442497d3a9314e591bc6969c87d6a7a00ac6189f660b3cd3176501fdeacdf57",
                  "abc11a5c2f04381b9b1d66238db3bc914f8f89d0130a7b1abae76b20af92c8b0",
                  "b8d0e4e50f144c5ae8392b52ab30ce67166918a8aa1acc282a3f144f83bafd85",
                  "f069b7f43f36f92d1db6cf90f6ff62393e8caddfc8a33c0708a6dccfece70a64",
                  "0a88ec2728fdea771fe86c59ae08e2f6b76a22ca2467e3024d31561c791f571a",
                  "fb80046d52fa1ee5fd9dcca24ccb5a7bd70b34727859d55dd74ffae6fa279548",
                  "3de11905d85b52f73b787d7360742e9f1b2b70fe5d6a3e812fcec8fe00211f09",
                  "856feb3dce681e971d4344b5cb3e34f7f91fcc7dc476d92b22da17405baef801",
                  "42ef31adef9a6397853af89d34a64d3909f1a8c0f1aba7aeee11e3e3d9ddb577",
                  "9514d09fc81aa4a98100924186e80a111591dfc1bdf23f1a09dbbf8991c58457", 
                  "5485ca7e2be4afc76aadd97536192cf2850228fe338083d6bab4c981bd6ddf92", 
                  "1cf0f867dec12c8a6c5caceeec86222e5c9af19a162c2ace0a33b2f5468e0c2a", 
                  "ba3538f2cbf933ba3f1b147714cbabd28a092b6ccadeb2f938e96bc18a8ca24f", 
                  "51cbf748d9baf1ecac292f451c0efe14d5068ea5d1ac036ff6b80e5dd580f093", 
                  "f2496377429303bac731b01afd1da4d34119505fc3c3eb3c6515654e840ada61", 
                  "9f2181f0bb4e411702856555cb2005e0775338b444fd4ec46a48bf189ad30b61", 
                  "34baf12ed8572e8d289562f71e8b0ec0c3acc3df10f20a47f9e454c86e8ea020", 
                  "d401821ff9d03779d0402171730b0de3fb7565fa7c0f4bdb178f9d1046646535", 
                  "42ef31adef9a6397853af89d34a64d3909f1a8c0f1aba7aeee11e3e3d9ddb577", 
                  "3614f7fc2457b7c5c8bc4e437850b00adf51ee2f65646597f4fe886d9645079d", 
                  "a087f9627bf0d88da197e34b340922e69c8b229b75c0a09e63742a0e35c2f97c", 
                  "293e3a0cbe6f38e96ab92021431e7cecf0df95386c24b3a28490e944fb9db0f2", 
                  "05d9fabebd65a07e3bea6512c59d59a1d47c72d12ca1828a1aefac0e38b7dadb", 
                  "52b196bbe9016488c735e7b41805b651261ffa5d7aa86eb6a1d0095be83687b2", 
                  "78d1760e7ead9d594cb0183e9632af761df9d4c46714bb92086d5de99351050d",
                  "6dfc55ccee952765f4e08e0776edff7e953f40ebf29edc1e382bb6d950bfd926",
                  "fc41e0c5941b69a28a751c8429fd377db2f4a3553c2141e4e5edc510ef71a3f0",
                  "6dfc55ccee952765f4e08e0776edff7e953f40ebf29edc1e382bb6d950bfd926",
                  "fc41e0c5941b69a28a751c8429fd377db2f4a3553c2141e4e5edc510ef71a3f0",
                  "843c5b54fdc1ea6d3ba85e89741bcc7e1b3299fa8509af4638d77958baee0d05",
                  "bebefa044c4953455037ee4c341030a667dec4ef3c9e892803fcaa75f499504e",
                  "0acc754bf7ef9d2ed456cc4208de353ffbb6aa0db745dcdd064dbbed55733380",
                  "38ca179d05c6cdf782c7c56f12f06c429f128867d0d878726df6bc44675be53b",
                  "d1efbf9c83ecb91fb68da965c6a3bcc6322c9c29aa629a4a4ece3c92c6f976c8",
                  "2653daafcf471d82e362572216b8b11ac37dc44c3baefc3c30a0c0c88f882af3",
                  "eb2695c91bc11b28eec70a54c86c9396956c044040be9bd6c0c766d3bb1a146f",
                  "d47a76be781cad5d7a2fbcc7fab759d8f362779ba923922000ee10676daa7154",
                  "5e0294f07728824c24e8262cce6e44656efe54905907cec58314ecc54b0ac273",
                  "ee949cef3e7daf1cb4c695ab642b9e93dfb67fd47b8d21b52ffd22aec801baf5",
                  "4b18f6bbf232545f3ebe0ebb92ab5a3a7aaf6f3d49b754b29712cce013418576",
                  "9ba043914816f776d96c392b6792b16b9370f8e9f6466040ab708357a9993a9e",
                  "df2b27c8bb3ecbbea46111e6357ea0380d0c476f3f214f1aa2c5052999397856") and
  not (process.name : "rundll32.exe" and process.args : "?:\\Windows\\system32\\davclnt.dll,DavSetCookie" and process.parent.name : "svchost.exe") and
  not (process.code_signature.trusted == true and
       process.code_signature.subject_name :
                ("RapidFire Tools Inc.", "Amazon Web Services, Inc.", "Quest Software Inc.",
                 "Chocolatey Software, Inc.", "ForeScout Technologies, Inc", "LogMeIn, Inc.",
                 "Elasticsearch, Inc.", "Oracle America, Inc.", "HP Inc", "Flexera Software LLC",
                 "Arcserve (USA) LLC", "Hewlett Packard", "Qualys, Inc", "Synology Inc.", "NoMachine S.a.r.l.", 
                 "Dell Technologies Inc.", "Guardicore Ltd.", "KASEYA US LLC", "Google LLC", "Johannes Schindelin", 
                 "Arcserve (USA) LLC", "Hewlett Packard", "LabTech Software", "Dell Inc", "HYCU, Inc.", "Trend Micro, Inc.",
                 "Block 64 Corporation")) and
  not (process.executable : "?:\\Windows\\System32\\WScript.exe" and process.args : "?:\\Windows\\system32\\slmgr.vbs" and
       process.parent.executable : "?:\\Windows\\system32\\wsmprovhost.exe") and
  not (process.pe.original_file_name : "DismHost.exe" and process.args : "{*}" and
       process.code_signature.subject_name : "Microsoft *" and process.code_signature.trusted == true) and
  not (process.args : "%TEMP%\\Spiceworks\\*" and process.parent.name : "wmiprvse.exe") and
  not (process.name : "wscript.exe" and process.command_line : "wscript*:\\Users\\*\\AppData\\Local\\Temp\\Spiceworks\\spiceworks_upload.vbs*") and
  not (process.executable : "?:\\Windows\\System32\\certutil.exe" and process.args : "-store" and process.args : "-enterprise") and 
  not (process.name : "certutil.exe" and process.args : ("-view", "-hashfile")) and
  not (process.name : "cmd.exe" and process.args : "%TEMP%\\Spiceworks\\spiceworks_upload.vbs") and
  not (process.executable : "C:\\Windows\\Microsoft.NET\\Framework64\\*\\installutil.exe" and
       process.args : "?:\\Program Files\\Omnyx\\Messagehandlers\\JobAgents\\*\\Omnyx.MessageHandler.Host.exe")
'''

min_endpoint_version = "8.6.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.001"
name = "PowerShell"
reference = "https://attack.mitre.org/techniques/T1059/001/"

[[threat.technique.subtechnique]]
id = "T1059.003"
name = "Windows Command Shell"
reference = "https://attack.mitre.org/techniques/T1059/003/"

[[threat.technique.subtechnique]]
id = "T1059.007"
name = "JavaScript"
reference = "https://attack.mitre.org/techniques/T1059/007/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1218"
name = "System Binary Proxy Execution"
reference = "https://attack.mitre.org/techniques/T1218/"
[[threat.technique.subtechnique]]
id = "T1218.005"
name = "Mshta"
reference = "https://attack.mitre.org/techniques/T1218/005/"

[[threat.technique.subtechnique]]
id = "T1218.010"
name = "Regsvr32"
reference = "https://attack.mitre.org/techniques/T1218/010/"

[[threat.technique.subtechnique]]
id = "T1218.011"
name = "Rundll32"
reference = "https://attack.mitre.org/techniques/T1218/011/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1021"
name = "Remote Services"
reference = "https://attack.mitre.org/techniques/T1021/"
[[threat.technique.subtechnique]]
id = "T1021.002"
name = "SMB/Windows Admin Shares"
reference = "https://attack.mitre.org/techniques/T1021/002/"



[threat.tactic]
id = "TA0008"
name = "Lateral Movement"
reference = "https://attack.mitre.org/tactics/TA0008/"

[internal]
min_endpoint_version = "8.6.0"
