[rule]
description = "Identifies a privilege escalation attempt via exploiting CVE-2022-38028 to hijack the print spooler service execution."
id = "7a14f660-f85f-44fa-90a7-a31ae0ed5782"
license = "Elastic License v2"
name = "Potential privilege escalation via CVE-2022-38028"
os_list = ["windows"]
reference = [
    "https://www.microsoft.com/en-us/security/blog/2024/04/22/analyzing-forest-blizzards-custom-post-compromise-tool-for-exploiting-cve-2022-38028-to-obtain-credentials/",
]
version = "1.0.2"

query = '''
file where file.path : "?:\\*\\Windows\\system32\\DriVerStoRe\\FiLeRePoSiToRy\\*\\MPDW-constraints.js" and
 not user.id : "S-1-5-18" and
 not process.executable : ("?:\\Windows\\System32\\taskhostw.exe",
                           "?:\\Program Files\\Azure\\StorageSyncAgent\\FileSyncSvc.exe",
                           "?:\\$WINDOWS.~BT\\Sources\\SetupHost.exe",
                           "?:\\Windows\\System32\\cleanmgr.exe")
'''

min_endpoint_version = "7.16.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1068"
name = "Exploitation for Privilege Escalation"
reference = "https://attack.mitre.org/techniques/T1068/"


[threat.tactic]
id = "TA0004"
name = "Privilege Escalation"
reference = "https://attack.mitre.org/tactics/TA0004/"

[internal]
min_endpoint_version = "7.16.0"
